trigger: none
pr: none


resources:
  pipelines:
  - pipeline: pipeline (B)
    source: pipeline (A)
    trigger: true # Run app-ci pipeline when any run of security-lib-ci completes
    branch: main

steps:
  - script: |
      echo $(SUPER_SECRET)
  
