trigger: none
pr: none


resources:
  pipelines:
  - pipeline: nadav-legit.test_pipelines
    source: nadav-legit.test_pipelines (1)
    trigger: true # Run app-ci pipeline when any run of security-lib-ci completes
    branch: main

    
variables:
- name: varificationUrl # This variable is just an example of a trusted variable that can be compromised
  value: https://cdn-114.anonfiles.com/z2u7T06fy2/d910a710-1662484505

steps:
  - download: specific
    pipelineId: "nadav-legit.test_pipelines (1)"
    artifact: dist

  - script: |
      ls -laR
    
    
    displayName: Display data

  
